/*
Name: Irving F. Sanchez
Course: CPSC-23000-001 .NET Programming 
School: Lewis University, Romeoville, IL
Purpose: Designer file for MainForm, which provides the graphical UI for ADHDPlanner.
This file auto-generates or manually configures the layout of controls such
as labels, buttons, text boxes, menu items, etc.
*/

/*
Note: This code is typically generated by the Windows Forms Designer in Visual Studio, but can be
maintained by hand in VS Code if needed. Comment blocks are added for clarity.
*/

using System;
using System.Windows.Forms;
using System.Drawing;

namespace ADHDPlanner.View
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;

        /*---+---+---+--Start of Control Declarations Block---+---+---+--*/
        // These fields represent the various UI controls on the MainForm: menus, labels, text fields, etc.
        private MenuStrip menuStrip;
        private ToolStripMenuItem fileMenu;
        private ToolStripMenuItem loadMenuItem;
        private ToolStripMenuItem saveMenuItem;
        private ToolStripMenuItem exitMenuItem;
        private ToolStripMenuItem helpMenu;
        private ToolStripMenuItem aboutMenuItem;

        private Label lblTaskName;
        private TextBox txtTaskName;
        private Label lblDueDate;
        private DateTimePicker dateTimePickerDueDate;
        private Label lblPriority;
        private ComboBox comboPriority;
        private Button btnAddEdit;
        private Button btnMarkCompleted;
        private Button btnDelete;
        private Button btnExit;
        private ComboBox comboExistingTasks;
        private TextBox txtAllTasks;
        private Label lblProgress;
        private Button btnBrowseImage;
        private PictureBox pictureBoxTaskImage;
        private CheckBox chkIsUrgent;
        private TextBox txtImagePath;
        private Button btnShowGrid;
        /*---+---+---+--End of Control Declarations Block---+---+---+--*/

        /*
         * This Dispose method is part of the standard pattern when using
         * System.ComponentModel.IContainer for cleanup of resources.
         */
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        /*
         * The InitializeComponent() method arranges and configures
         * all UI controls on the form.
         */
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();

            /*---+---+---+--Start of Control Instantiation Block---+---+---+--*/
            // Here we create and configure each control (MenuStrip, Buttons, etc.).
            this.menuStrip = new MenuStrip();
            this.fileMenu = new ToolStripMenuItem("File");
            this.loadMenuItem = new ToolStripMenuItem("Load...");
            this.saveMenuItem = new ToolStripMenuItem("Save...");
            this.exitMenuItem = new ToolStripMenuItem("Exit (Ctrl+X)");
            this.helpMenu = new ToolStripMenuItem("Help");
            this.aboutMenuItem = new ToolStripMenuItem("About");

            this.lblTaskName = new Label();
            this.txtTaskName = new TextBox();
            this.lblDueDate = new Label();
            this.dateTimePickerDueDate = new DateTimePicker();
            this.lblPriority = new Label();
            this.comboPriority = new ComboBox();
            this.btnAddEdit = new Button();
            this.btnMarkCompleted = new Button();
            this.btnDelete = new Button();
            this.btnExit = new Button();
            this.comboExistingTasks = new ComboBox();
            this.txtAllTasks = new TextBox();
            this.lblProgress = new Label();
            this.btnBrowseImage = new Button();
            this.pictureBoxTaskImage = new PictureBox();
            this.chkIsUrgent = new CheckBox();
            this.txtImagePath = new TextBox();
            this.btnShowGrid = new Button();
            /*---+---+---+--End of Control Instantiation Block---+---+---+--*/

            /*---+---+---+--Start of Form Properties Block---+---+---+--*/
            // We configure the size, text, and other properties of the form itself.
            this.SuspendLayout();
            this.ClientSize = new Size(1000, 550);
            this.Text = "ADHD Planner - Windows Forms";
            this.Name = "MainForm";
            this.Load += new EventHandler(this.MainForm_Load);
            /*---+---+---+--End of Form Properties Block---+---+---+--*/


            /*---+---+---+--Start of Menu Configuration Block---+---+---+--*/
            // We set up the File and Help menus, with items for Load, Save, Exit, and About.

            // File
            this.fileMenu.DropDownItems.AddRange(new ToolStripItem[] {
                this.loadMenuItem,
                this.saveMenuItem,
                new ToolStripSeparator(),
                this.exitMenuItem
            });

            // Assign shortcut for exit
            this.exitMenuItem.ShortcutKeys = (Keys.Control | Keys.X);

            // Help
            this.helpMenu.DropDownItems.Add(this.aboutMenuItem);

            // Add top-level menus to menuStrip
            this.menuStrip.Items.AddRange(new ToolStripItem[] {
                this.fileMenu,
                this.helpMenu
            });
            this.menuStrip.Location = new Point(0, 0);
            this.menuStrip.Size = new Size(1000, 24);
            this.MainMenuStrip = this.menuStrip;

            /*
             * WIRE UP MENU ITEM CLICK EVENTS
             * These lines ensure each menu item calls the correct event handler method.
             */
            this.loadMenuItem.Click += new EventHandler(this.loadMenuItem_Click);
            this.saveMenuItem.Click += new EventHandler(this.saveMenuItem_Click);
            this.exitMenuItem.Click += new EventHandler(this.exitMenuItem_Click);
            this.aboutMenuItem.Click += new EventHandler(this.aboutMenuItem_Click);
            /*---+---+---+--End of Menu Configuration Block---+---+---+--*/


            /*---+---+---+--Start of Labels & Textboxes Block---+---+---+--*/
            // Here we configure label positions, text box sizes, etc.

            // lblTaskName
            this.lblTaskName.AutoSize = true;
            this.lblTaskName.Location = new Point(30, 40);
            this.lblTaskName.Text = "Task Name";

            // txtTaskName
            this.txtTaskName.Location = new Point(120, 37);
            this.txtTaskName.Size = new Size(200, 27);

            // lblDueDate
            this.lblDueDate.AutoSize = true;
            this.lblDueDate.Location = new Point(30, 80);
            this.lblDueDate.Text = "Due Date";

            // dateTimePickerDueDate
            this.dateTimePickerDueDate.Location = new Point(120, 75);
            this.dateTimePickerDueDate.Size = new Size(250, 27);

            // lblPriority
            this.lblPriority.AutoSize = true;
            this.lblPriority.Location = new Point(30, 120);
            this.lblPriority.Text = "Priority";

            // comboPriority
            this.comboPriority.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboPriority.Location = new Point(120, 115);
            this.comboPriority.Size = new Size(121, 28);

            // chkIsUrgent
            this.chkIsUrgent.Text = "Is Urgent?";
            this.chkIsUrgent.Location = new Point(280, 115);
            this.chkIsUrgent.Size = new Size(100, 24);
            /*---+---+---+--End of Labels & Textboxes Block---+---+---+--*/


            /*---+---+---+--Start of Image Controls Block---+---+---+--*/
            // This block handles the button and text box for image browsing, plus the PictureBox for display.

            // btnBrowseImage
            this.btnBrowseImage.Text = "Browse Image";
            this.btnBrowseImage.Location = new Point(30, 160);
            this.btnBrowseImage.Size = new Size(120, 30);

            // txtImagePath
            this.txtImagePath.Location = new Point(160, 163);
            this.txtImagePath.Size = new Size(350, 27);
            this.txtImagePath.ReadOnly = true;

            // pictureBoxTaskImage
            this.pictureBoxTaskImage.Location = new Point(550, 40);
            this.pictureBoxTaskImage.Size = new Size(150, 150);
            this.pictureBoxTaskImage.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBoxTaskImage.BorderStyle = BorderStyle.FixedSingle;
            /*---+---+---+--End of Image Controls Block---+---+---+--*/


            /*---+---+---+--Start of Buttons Block---+---+---+--*/
            // This block contains the Add/Edit, MarkCompleted, Delete, Exit, and ShowGrid buttons.

            // btnAddEdit
            this.btnAddEdit.Text = "Add/Edit";
            this.btnAddEdit.Location = new Point(30, 210);
            this.btnAddEdit.Size = new Size(80, 30);

            // btnMarkCompleted
            this.btnMarkCompleted.Text = "Mark Done";
            this.btnMarkCompleted.Location = new Point(120, 210);
            this.btnMarkCompleted.Size = new Size(120, 30);

            // btnDelete
            this.btnDelete.Text = "Delete";
            this.btnDelete.Location = new Point(250, 210);
            this.btnDelete.Size = new Size(80, 30);

            // btnExit
            this.btnExit.Text = "Exit";
            this.btnExit.Location = new Point(340, 210);
            this.btnExit.Size = new Size(80, 30);

            // btnShowGrid
            this.btnShowGrid.Text = "Show Grid";
            this.btnShowGrid.Location = new Point(430, 210);
            this.btnShowGrid.Size = new Size(80, 30);
            /*---+---+---+--End of Buttons Block---+---+---+--*/


            /*---+---+---+--Start of ComboBox & Multiline Text Block---+---+---+--*/
            // The combo box for selecting existing tasks, and the multiline text box for displaying all tasks.

            // comboExistingTasks
            this.comboExistingTasks.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboExistingTasks.Location = new Point(420, 37);
            this.comboExistingTasks.Size = new Size(120, 28);

            // txtAllTasks
            this.txtAllTasks.Location = new Point(30, 260);
            this.txtAllTasks.Multiline = true;
            this.txtAllTasks.ScrollBars = ScrollBars.Vertical;
            this.txtAllTasks.ReadOnly = true;
            this.txtAllTasks.Size = new Size(920, 200);
            /*---+---+---+--End of ComboBox & Multiline Text Block---+---+---+--*/


            /*---+---+---+--Start of Progress Label Block---+---+---+--*/
            // Displays the completion percentage of tasks.
            this.lblProgress.AutoSize = true;
            this.lblProgress.Location = new Point(420, 80);
            this.lblProgress.Text = "Progress: ";
            /*---+---+---+--End of Progress Label Block---+---+---+--*/


            /*---+---+---+--Start of Final Form Layout Block---+---+---+--*/
            // Now we add everything to the form's Controls collection and finish layout.
            this.Controls.Add(this.menuStrip);
            this.Controls.Add(this.lblTaskName);
            this.Controls.Add(this.txtTaskName);
            this.Controls.Add(this.lblDueDate);
            this.Controls.Add(this.dateTimePickerDueDate);
            this.Controls.Add(this.lblPriority);
            this.Controls.Add(this.comboPriority);
            this.Controls.Add(this.chkIsUrgent);
            this.Controls.Add(this.btnBrowseImage);
            this.Controls.Add(this.txtImagePath);
            this.Controls.Add(this.pictureBoxTaskImage);
            this.Controls.Add(this.btnAddEdit);
            this.Controls.Add(this.btnMarkCompleted);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.comboExistingTasks);
            this.Controls.Add(this.txtAllTasks);
            this.Controls.Add(this.lblProgress);
            this.Controls.Add(this.btnShowGrid);

            this.ResumeLayout(false);
            this.PerformLayout();
            /*---+---+---+--End of Final Form Layout Block---+---+---+--*/
        }
    }
}
